version: '3.8'
services:
  data_historical:
    build:
      context: ./
      args:
        DATA_DIR: ${DATA_DIR:-./data}  # Default to ./data if not specified
    volumes:
      - ./data/historical/alembic.ini:/code/alembic.ini
      - ./data/historical/migrations:/code/migrations
    ports:
      - "80:80"
    env_file:
      - .env
      - ./data/historical/.env
    environment:
      - DATABASE_URL=${DATABASE_URL:-postgresql://postgres:password@db:5432/postgres}
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ${DATA_DIR:-./data}/postgres:/var/lib/postgresql/data
