services:
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    ports:
      - "${POSTGRES_UI_PORT}:80"  # Map the container's port 80 to localhost:5050
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres
    volumes:
      - ${DATA_DIR:-./volume_data}/pgadmin:/var/lib/postgresql/data
    security_opt:
      - "no-new-privileges:true"
    read_only: true

  redpanda:
    image: docker.redpanda.com/redpandadata/console:latest
    ports:
      - "${BROKER_UI_PORT}:8080"
    environment:
      - KAFKA_BROKERS=kafka:9092
    depends_on:
      - kafka
    security_opt:
      - "no-new-privileges:true"
    read_only: true

  data_store:
    build:
      target: dev_image
    read_only: true
    volumes:
      - ./data/store/app:/code/data/store/app
      - ./common:/code/common
      - ./routers:/code/routers
      - ./schemas:/code/schemas
    environment:
      - LOG_LEVEL=debug
    image: trader_joe_data_store:dev

  data_ingest:
    build:
      target: dev_image
    volumes:
      - ./data/ingest/app:/code/data/ingest/app
      - ./common:/code/common
      - ./routers:/code/routers
      - ./schemas:/code/schemas
    environment:
      - LOG_LEVEL=debug
    image: trader_joe_data_ingest:dev