version: '3.8'
services:
  data_historical:
    build:
      context: ./data/historical
      args:
        DATA_DIR: ${DATA_DIR:-./data}  # Default to ./data if not specified
    command: uvicorn app.main:app --host 0.0.0.0 --port 80 --reload
    volumes:
      - ./app:/code/app
    ports:
      - "80:80"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/postgres
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ${DATA_DIR:-./data}/postgres:/var/lib/postgresql/data

volumes:
  pgdata:
