version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: ${DATABASE_NAME}
    ports:
      - "${DATABASE_PORT}:5432"
    env_file:
      - .env
      - ./data/store/.env
    environment:
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
    volumes:
      - ${DATA_DIR:-./volume_data}/postgres:/var/lib/postgresql/data

  kafka:
    image: confluentinc/cp-kafka:latest  # Make sure the version supports KRaft
    container_name: ${BROKER_NAME}
    ports:
      - "${BROKER_PORT}:9092"
    env_file:
      - .env
      - ./data/ingest/.env
    environment:
      CLUSTER_ID: ${KAFKA_ID}
      KAFKA_LISTENERS: BROKER://0.0.0.0:9092,CONTROLLER://${BROKER_NAME}:9093
      KAFKA_ADVERTISED_LISTENERS: BROKER://localhost:9092
      # KAFKA_LISTENERS: BROKER://${BROKER_NAME}:${BROKER_PORT},EXTERNAL://${BROKER_NAME}:9092,CONTROLLER://${BROKER_NAME}:9093
      # KAFKA_ADVERTISED_LISTENERS: BROKER://${BROKER_NAME}:${BROKER_PORT},EXTERNAL://${BROKER_NAME}:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,BROKER:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_PROCESS_ROLES: 'controller,broker'
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@${BROKER_NAME}:9093'  #,2@kafka2:9093,3@kafka3:9093
      KAFKA_LOG_DIRS: '/var/lib/kafka/data'
    volumes:
      - ${DATA_DIR:-./volume_data}/kafka:/var/lib/kafka/data

  data_store:
    build:
      context: ./
      target: data_store
      # args:
      #   DATA_DIR: ${DATA_DIR:-./data}
    volumes:
      - ./data/store/alembic.ini:/code/alembic.ini
      - ./data/store/migrations:/code/migrations
    ports:
      - "8080:80"
    env_file:
      - .env
      - ./data/store/.env
    environment:
      - DATABASE_URL=${DATABASE_URL:-postgresql://postgres:password@db:5432/postgres}
    depends_on:
      - postgres

  data_ingest:
    build:
      context: ./
      target: data_ingest
    ports:
      - "8081:80"
    env_file:
      - .env
      - ./data/ingest/.env
    depends_on:
      - kafka
