version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: ${DATABASE_NAME}
    ports:
      - "${DATABASE_PORT}:5432"
    env_file:
      - .env
      - ./data/store/.env
    environment:
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
    volumes:
      - ${DATA_DIR:-./volume_data}/postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    ports:
      - "${POSTGRES_UI_PORT}:80"  # Map the container's port 80 to localhost:5050
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres
    volumes:
      - ${DATA_DIR:-./volume_data}/pgadmin:/var/lib/postgresql/data

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: ${BROKER_NAME}
    ports:
      - "${BROKER_PORT}:9092"
    env_file:
      - .env
      - ./data/ingest/.env
    environment:
      CLUSTER_ID: ${KAFKA_ID}
      KAFKA_LISTENERS: BROKER://0.0.0.0:9092,CONTROLLER://${BROKER_NAME}:9093
      KAFKA_ADVERTISED_LISTENERS: BROKER://${BROKER_NAME}:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,BROKER:PLAINTEXT
      KAFKA_PROCESS_ROLES: 'controller,broker'
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@${BROKER_NAME}:9093'
      KAFKA_LOG_DIRS: '/var/lib/kafka/data'
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"  # Optional: Enable dynamic topic creation
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - ${DATA_DIR:-./volume_data}/kafka:/var/lib/kafka/

  redpanda:
    image: docker.redpanda.com/redpandadata/console:latest
    ports:
      - "${BROKER_UI_PORT}:8080"
    environment:
      - KAFKA_BROKERS=kafka:9092
    depends_on:
      - kafka

  data_store:
    build:
      context: ./
      target: data_store
    hostname: ${DATA_STORE_NAME:-data_store}
    ports:
      - "${DATA_STORE_PORT}:${APP_INTERNAL_PORT}"
    volumes:
      - ./data/store/alembic.ini:/code/alembic.ini
      - ./data/store/migrations:/code/migrations
    env_file:
      - .env
      - ./data/store/.env
    environment:
      - DATABASE_URI=${DATABASE_URI:-postgresql://postgres:password@db:5432/postgres}
      - LOG_LEVEL=debug
    depends_on:
      - postgres

  data_ingest:
    build:
      context: ./
      target: data_ingest
    hostname: ${DATA_INGEST_NAME:-data_ingest}
    ports:
      - "${DATA_INGEST_PORT}:${APP_INTERNAL_PORT}"
    env_file:
      - .env
      - ./data/ingest/.env
    environment:
      - LOG_LEVEL=debug
    depends_on:
      - kafka
