version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ${DATABASE_NAME:-postgres}
      POSTGRES_USER: ${DATABASE_USER:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASS:-password}
    ports:
      - "${DATABASE_PORT:-5432}:5432"
    volumes:
      - ${DATA_DIR:-./data}/postgres:/var/lib/postgresql/data
  data_store:
    build:
      context: ./
      target: data_store
      args:
        DATA_DIR: ${DATA_DIR:-./data}
    volumes:
      - ./data/store/alembic.ini:/code/alembic.ini
      - ./data/store/migrations:/code/migrations
    ports:
      - "8080:80"
    env_file:
      - .env
      - ./data/store/.env
    environment:
      - DATABASE_URL=${DATABASE_URL:-postgresql://postgres:password@db:5432/postgres}
    depends_on:
      - db
  data_ingest:
    build:
      context: ./
      target: data_ingest
    ports:
      - "8081:80"
    env_file:
      - .env
      - ./data/ingest/.env  
