"""Initial migration

Revision ID: 13fc73adb286
Revises: 
Create Date: 2024-12-10 20:42:06.789277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13fc73adb286'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_market_activity_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('granularity', sa.Enum('ONE_MINUTE', 'FIVE_MINUTES', 'ONE_HOUR', 'ONE_DAY', 'ONE_WEEK', 'ONE_MONTH', name='granularity'), nullable=False),
    sa.Column('source', sa.Enum('IB_API', 'ALPACA_API', 'MANUAL_ENTRY', name='datasource'), nullable=False),
    sa.Column('split_factor', sa.Float(), nullable=False),
    sa.Column('dividends_factor', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_market_activity_data_datetime'), 'stock_market_activity_data', ['datetime'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_market_activity_data_datetime'), table_name='stock_market_activity_data')
    op.drop_table('stock_market_activity_data')
    # ### end Alembic commands ###
