"""Initial migration

Revision ID: a62667a6c4d8
Revises: 
Create Date: 2024-11-20 18:14:24.381264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a62667a6c4d8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_price_volume',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('granularity', sa.Enum('ONE_MINUTE', 'FIVE_MINUTES', 'ONE_HOUR', 'ONE_DAY', name='granularity'), nullable=False),
    sa.Column('source', sa.Enum('BROKER_API', 'MANUAL_ENTRY', 'AUTOMATED_SYSTEM', name='datasource'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_price_volume_datetime'), 'stock_price_volume', ['datetime'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_price_volume_datetime'), table_name='stock_price_volume')
    op.drop_table('stock_price_volume')
    # ### end Alembic commands ###
